pull_request_rules:
  - name: automatic merge
    actions:
      merge:
        method: rebase
        rebase_fallback: merge
        strict: true
    conditions:
    - label!=work-in-progress
    - '#approved-reviews-by>=1'
    - status-success=Travis CI - Pull Request
  - name: automatic merge backports from Mergify
    actions:
      merge:
        method: rebase
        rebase_fallback: merge
        strict: true
    conditions:
    - base~=^stable/.*
    - label!=work-in-progress
    - author=mergify[bot]
    - status-success=Travis CI - Pull Request
  - name: dismiss reviews on additional commit
    actions:
      dismiss_reviews: {}
    conditions: []

# Backports to stable branches
  - actions:
      backport:
        branches:
        - stable/3.0
    conditions:
    - label=backport-to-3.0
    name: backport stable/3.0
  - actions:
      backport:
        branches:
        - stable/3.1
    conditions:
    - label=backport-to-3.1
    name: backport stable/3.1
  - actions:
      backport:
        branches:
        - stable/4.0
    conditions:
    - label=backport-to-4.0
    name: backport stable/4.0
  - actions:
      backport:
        branches:
        - stable/4.1
    conditions:
    - label=backport-to-4.1
    name: backport stable/4.1
  - actions:
      backport:
        branches:
        - stable/4.2
    conditions:
    - label=backport-to-4.2
    name: backport stable/4.2
  - actions:
      backport:
        branches:
        - stable/4.3
    conditions:
    - label=backport-to-4.3
    name: backport stable/4.3
