queue_rules:
  - name: default
    conditions:
    - check-success=doc (docs)
    - check-success=doc (docs-gnocchi-web)
    - check-success=check (build)
    - check-success=check (pep8)
    - check-success=test (py38, mysql-ceph-upgrade-from-4.4)
    - check-success=test (py38, postgresql-file-upgrade-from-4.4)
    - check-success=test (py38, mysql-file)
    - check-success=test (py38, mysql-swift)
    - check-success=test (py38, mysql-s3)
    - check-success=test (py38, mysql-ceph)
    - check-success=test (py38, postgresql-file)
    - check-success=test (py38, postgresql-swift)
    - check-success=test (py38, postgresql-s3)
    - check-success=test (py38, postgresql-ceph)
    - check-success=test (py39, postgresql-file-upgrade-from-4.4)
    - check-success=test (py39, mysql-file)
    - check-success=test (py39, mysql-swift)
    - check-success=test (py39, mysql-s3)
    - check-success=test (py39, postgresql-file)
    - check-success=test (py39, postgresql-swift)
    - check-success=test (py39, postgresql-s3)
    - check-success=test (py311, postgresql-file-upgrade-from-4.4)
    - check-success=test (py311, mysql-file)
    - check-success=test (py311, mysql-swift)
    - check-success=test (py311, mysql-s3)
    - check-success=test (py311, postgresql-file)
    - check-success=test (py311, postgresql-swift)
    - check-success=test (py311, postgresql-s3)

pull_request_rules:
  - name: automatic merge
    actions:
      queue:
        method: merge
        name: default
    conditions:
    - label!=work-in-progress
    - '#approved-reviews-by>=1'
    - check-success=doc (docs)
    - check-success=doc (docs-gnocchi-web)
    - check-success=check (build)
    - check-success=check (pep8)
    - check-success=test (py38, mysql-ceph-upgrade-from-4.4)
    - check-success=test (py38, postgresql-file-upgrade-from-4.4)
    - check-success=test (py38, mysql-file)
    - check-success=test (py38, mysql-swift)
    - check-success=test (py38, mysql-s3)
    - check-success=test (py38, mysql-ceph)
    - check-success=test (py38, postgresql-file)
    - check-success=test (py38, postgresql-swift)
    - check-success=test (py38, postgresql-s3)
    - check-success=test (py38, postgresql-ceph)
    - check-success=test (py39, postgresql-file-upgrade-from-4.4)
    - check-success=test (py39, mysql-file)
    - check-success=test (py39, mysql-swift)
    - check-success=test (py39, mysql-s3)
    - check-success=test (py39, postgresql-file)
    - check-success=test (py39, postgresql-swift)
    - check-success=test (py39, postgresql-s3)
    - check-success=test (py311, postgresql-file-upgrade-from-4.4)
    - check-success=test (py311, mysql-file)
    - check-success=test (py311, mysql-swift)
    - check-success=test (py311, mysql-s3)
    - check-success=test (py311, postgresql-file)
    - check-success=test (py311, postgresql-swift)
    - check-success=test (py311, postgresql-s3)

  - name: automatic merge backports from Mergify
    actions:
      queue:
        method: merge
        name: default
    conditions:
    - base~=^stable/.*
    - label!=work-in-progress
    - author=mergify[bot]

  - name: dismiss reviews on additional commit
    actions:
      dismiss_reviews: {}
    conditions: []

# Backports to stable branches
  - actions:
      backport:
        branches:
        - stable/4.4
    conditions:
    - label=backport-to-4.4
    name: backport stable/4.4

  - actions:
      backport:
        branches:
        - stable/4.5
    conditions:
    - label=backport-to-4.5
    name: backport stable/4.5
