FROM ubuntu:22.04
ENV GNOCCHI_WORKSPACE /github/workspace
ENV DEBIAN_FRONTEND noninteractive

#NOTE(tobias-urdin): need gnupg for apt-key
RUN apt-get update -y && apt-get install -qy gnupg software-properties-common
RUN add-apt-repository -y ppa:deadsnakes/ppa
RUN apt-get update -y && apt-get install -qy \
        ca-certificates \
        locales \
        git \
        wget \
        curl \
        python3 \
        python3-dev \
        python3-pip \
        python3.9 \
        python3.9-dev \
        python3.9-distutils \
        python3.11 \
        python3.11-dev \
# Needed for uwsgi core routing support
        build-essential \
        libffi-dev \
        libpq-dev \
        postgresql \
        memcached \
        mysql-client \
        mysql-server \
# For Ceph
        librados-dev \
        liberasurecode-dev \
        python3-rados \
        ceph \
# For prometheus
        libsnappy-dev \
        libprotobuf-dev \
# For redis
        redis-server

RUN rm -rf /var/lib/apt/lists/*

# Node
ENV NVM_VERSION v0.40.8
ENV NODE_VERSION 24.21.0
ENV NVM_DIR /opt/.nvm
ENV PATH $NVM_DIR/versions/node/v${NODE_VERSION}/bin:$PATH

RUN echo "NVM_VERSION=${NVM_VERSION}" && echo "NODE_VERSION=${NODE_VERSION}"
RUN mkdir -p $NVM_DIR
RUN curl -fsSL "https://raw.githubusercontent.com/nvm-sh/nvm/${NVM_VERSION}/install.sh" | bash
RUN ls -la "${NVM_DIR}" && . "${NVM_DIR}/nvm.sh" && nvm --version
RUN . "${NVM_DIR}/nvm.sh" && nvm install "${NODE_VERSION}"

RUN ln -sf "${NVM_DIR}/versions/node/v${NODE_VERSION}/bin/node" /usr/local/bin/node \
    && ln -sf "${NVM_DIR}/versions/node/v${NODE_VERSION}/bin/npm" /usr/local/bin/npm \
    && ln -sf "${NVM_DIR}/versions/node/v${NODE_VERSION}/bin/npx" /usr/local/bin/npx

RUN node --version && npm --version

# NOTE(tobias.urdin): hack since pyparsing in site-packages collides with our requirements
RUN rm -rf /usr/lib/python3/dist-packages/pyparsing*

# NOTE(tobias.urdin): hack since jaracoin site-packages collides with our requirements
RUN rm -rf /usr/lib/python3/dist-packages/jaraco*

# TODO(tobias.urdin): hack remove this when we drop python 3.9
RUN sed -i '1s/^/from __future__ import annotations\n/' /usr/lib/python3/dist-packages/werkzeug/sansio/utils.py

#NOTE(sileht): really no utf-8 in 2017 !?
ENV LANG en_US.UTF-8
RUN update-locale
RUN locale-gen $LANG

#NOTE(sileht): Upgrade python dev tools
RUN python3 -m pip install -U pip tox virtualenv

RUN npm install s3rver@3.7.0 --global

RUN groupadd --gid 1001 tester
RUN useradd --uid 1001 --gid 1001 --home-dir $GNOCCHI_WORKSPACE --shell /bin/bash tester
USER tester

COPY entrypoint.sh.ci /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
